@apiURL = http://localhost:4000/api/v1

####
POST {{apiURL}}/checkout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InlAZ21haWwuY29tIiwiaWF0IjoxNzU3ODQzOTg0LCJleHAiOjE3NTc4NDc1ODR9._3OGWhklr8fd_2B7bl5viWh4GBbEhHt4rHIpqfpzscM

{
  "amount": 500 
}


####
GET {{apiURL}}/book/featured-books